name: Deploy static content to Pages

on:
  push:
    branches: ['main']

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: './Vakya/frontend/package-lock.json'

      - name: Install dependencies
        working-directory: ./Vakya/frontend
        run: npm ci

      - name: Build
        working-directory: ./Vakya/frontend
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './Vakya/frontend/dist'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
